package com.project.framework

import java.time.LocalDateTime
import java.util.UUID

object GenerateFakeData {
    fun generateFakeTaskList(): List<Task> {
        return listOf<Task>(
            Task(
                taskId = UUID.randomUUID(),
                botId = null,
                LocalDateTime.of(2024, 12, 4, 12, 45),
                LocalDateTime.of(2024, 12, 4, 12, 50),
                4,
                6,
                15,
                2,
                1,
                8,
                FatalError.E_STUCK,
                null,
                null,
                "DG",
                null,
                true
            ),
            Task(
                UUID.randomUUID(),
                1842,
                LocalDateTime.of(2024, 12, 4, 12, 58),
                LocalDateTime.of(2024, 12, 4, 13, 5),
                3,
                3,
                12,
                null,
                null,
                null,
                FatalError.E_STUCK,
                "Check location, traction drive fault",
                null,
                "DG",
                null,
                true
            ),
            Task(
                UUID.randomUUID(),
                2031,
                LocalDateTime.of(2024, 12, 4, 13, 2),
                LocalDateTime.of(2024, 12, 4, 13, 10),
                2,
                8,
                null,
                null,
                3,
                13,
                FatalError.E_STUCK,
                null,
                null,
                "DG",
                null,
                true
            ),
            Task(
                UUID.randomUUID(),
                2010,
                LocalDateTime.of(2024, 12, 4, 13, 15),
                null,
                1,
                13,
                null,
                null,
                2,
                8,
                FatalError.E_COLLISION,
                "Possible collision with chimney",
                null,
                "DG",
                null,
                false
            ),
            Task(
                UUID.randomUUID(),
                2008,
                LocalDateTime.of(2024, 12, 4, 13, 21),
                null,
                2,
                8,
                null,
                null,
                3,
                2,
                FatalError.E_STUCK,
                null,
                null,
                "DG",
                null,
                false
            ),
            Task(
                UUID.randomUUID(),
                1983,
                LocalDateTime.of(2024, 12, 4, 13, 25),
                LocalDateTime.of(2024, 12, 4, 13, 30),
                3,
                15,
                11,
                null,
                null,
                null,
                FatalError.E_ESTOP,
                null,
                null,
                "DG",
                null,
                true
            ),
            Task(
                UUID.randomUUID(),
                3043,
                LocalDateTime.of(2024, 12, 4, 14, 1),
                null,
                2,
                3,
                null,
                null,
                20,
                null,
                FatalError.E_OVERHANG,
                null,
                null,
                "DG",
                null,
                false
            ),
            Task(
                UUID.randomUUID(),
                1910,
                LocalDateTime.of(2024, 12, 4, 14, 9),
                LocalDateTime.of(2024, 12, 4, 14, 30),
                1,
                16,
                2,
                null,
                1,
                null,
                FatalError.E_STUCK,
                "Check for debris",
                "Found and remove debris",
                "DG",
                "MG",
                true
            ),
            Task(
                UUID.randomUUID(),
                1849,
                LocalDateTime.of(2024, 12, 4, 14, 32),
                LocalDateTime.of(2024, 12, 4, 14, 41),
                3,
                8,
                null,
                null,
                null,
                5,
                FatalError.E_OVERHANG,
                "stp @ 2:40",
                "Pushed",
                "DG",
                "MG",
                true
            ),
            Task(
                UUID.randomUUID(),
                1820,
                LocalDateTime.of(2024, 12, 4, 15, 2),
                LocalDateTime.of(2024, 12, 4, 15, 10),
                3,
                9,
                null,
                null,
                2,
                8,
                FatalError.E_STUCK,
                null,
                null,
                "DG",
                null,
                true
            ),
            Task(
                UUID.randomUUID(),
                1834,
                LocalDateTime.of(2024, 12, 4, 15, 28),
                null,
                4,
                6,
                null,
                null,
                3,
                15,
                FatalError.E_STUCK,
                "Pass down to next shift",
                null,
                "DG",
                null,
                false
            ),
        )
    }
}